[features]
seeds = false
skip-lint = false
[programs.devnet]
learning_solana = "F2yGB1QSPjuaqquyWRqE9g1fmYdugupd8iukUVNp4ocA"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/marissabiesecker/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
